// Generated by CoffeeScript 1.6.2
module('Чтение и запись cookies');

test('autoload', function() {
  alert(document.cookie);
  return ok($.cookie('test'), 'test 1');
});

test('simple value', function() {
  $.cookie('test', 'go', {
    expires: 7
  });
  alert(document.cookie);
  return ok($.cookie('test'), 'test 2');
});

test('Проверка работы cookies в приложении', function() {
  ok($.cookie('last_href'), 'Сохранение cookies при переходах по страницам');
  return ok($.cookie('contacts'), 'Сохранение cookies после закрытия программы');
});

module('Проверка целостности пакета');

test('Проверка наличия файлов-настроек в пакете', function() {
  var sn;

  sn = $('#sn').data('sn');
  ok(sn.conf.main != null, '/conf/main.json');
  ok(sn.conf.theme != null, '/conf/themes.json');
  return ok(sn.conf.settings != null, '/conf/settings.json');
});

test('Проверка на наличиние необходимых библиотек', function() {
  ok(window.jQuery != null, 'jQuery');
  ok(window.EJS != null, 'EJS');
  ok(window.jQuery.cookie != null, 'jquery.cookie');
  return ok(window.jQuery.isFunction($.bootstrapIE6) != null, 'bootstrap-ie6');
});

test('Проверка на наличиние необходимых шаблонов и текстов', function() {
  var sn;

  sn = $('#sn').data('sn');
  ok($('#bar').length, 'layout/' + sn.region.name + '/bar.html');
  ok($('#main').length, 'layout/' + sn.region.name + '/main.html');
  ok($('#primary').length, 'content/' + sn.region.name + '/main.html');
  return ok($('#side').length, 'content/' + sn.region.name + '/side_main-dev.html');
});
