// Generated by CoffeeScript 1.6.2
test("Проверка работы cookies", function() {
  var sn;

  sn = $('#sn').data('sn');
  ok($.cookie('last_href'), "Сохрание cookie при переходах по страница");
  return ok($.cookie('contacts'), "Сохрание cookie после закрытия программы");
});

test("Проверка наличия файлов-настроек в пакете", function() {
  $.ajax({
    url: 'conf/main.json',
    async: false,
    dataType: 'json',
    success: function(s) {
      return ok(s != null, "Наличие /conf/main.json");
    }
  });
  $.ajax({
    url: 'conf/themes.json',
    async: false,
    dataType: 'json',
    success: function(s) {
      return ok(s != null, "Наличие /conf/themes.json");
    }
  });
  return $.ajax({
    url: 'conf/settings.json',
    async: false,
    dataType: 'json',
    success: function(s) {
      return ok(s != null, "Наличие /conf/settings.json");
    }
  });
});
